.TH "_DIO_PACKET_PORTACCESS" 3 "Sun Mar 10 2019" "DIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_DIO_PACKET_PORTACCESS \- Port access packet structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dioctl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ULONG \fBCount\fP"
.br
.RI "Count of DIO_PORTACCESS_ENTRY\&. "
.ti -1c
.RI "\fBDIO_PORTACCESS_ENTRY\fP \fBEntry\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Port access packet structure\&. 

Contains one or multiple port address ranges\&.
.br

.PP
Definition at line 36 of file dioctl\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "ULONG _DIO_PACKET_PORTACCESS::Count"

.PP
Count of DIO_PORTACCESS_ENTRY\&. 
.PP
Definition at line 37 of file dioctl\&.h\&.
.SS "\fBDIO_PORTACCESS_ENTRY\fP _DIO_PACKET_PORTACCESS::Entry[]"

.PP
Definition at line 38 of file dioctl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DIO from the source code\&.
