.TH "_DIO_PACKET" 3 "Sun Mar 10 2019" "DIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_DIO_PACKET \- IOCTL packet\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dioctl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDIO_PACKET_PORTACCESS\fP \fBPortAccess\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
IOCTL packet\&. 
.PP
Definition at line 47 of file dioctl\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDIO_PACKET_PORTACCESS\fP _DIO_PACKET::PortAccess"

.PP
Definition at line 48 of file dioctl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DIO from the source code\&.
