.TH "_IO_ACCESS_MAP" 3 "Sun Mar 10 2019" "DIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_IO_ACCESS_MAP
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iomap\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UCHAR \fBMap\fP [8192]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file iomap\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "UCHAR _IO_ACCESS_MAP::Map[8192]"

.PP
Definition at line 5 of file iomap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DIO from the source code\&.
