.TH "Include/dioctl.h" 3 "Sun Mar 10 2019" "DIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Include/dioctl.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_DIO_PORTACCESS_ENTRY\fP"
.br
.RI "Port access entry structure\&. "
.ti -1c
.RI "struct \fB_DIO_PACKET_PORTACCESS\fP"
.br
.RI "Port access packet structure\&. "
.ti -1c
.RI "union \fB_DIO_PACKET\fP"
.br
.RI "IOCTL packet\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDIO_IOCODE_SET_PORTACCESS\fP   0x801"
.br
.ti -1c
.RI "#define \fBDIO_IOCODE_RESET_PORTACCESS\fP   0x802"
.br
.ti -1c
.RI "#define \fBDIO_IOCTL_SET_PORTACCESS\fP   CTL_CODE(FILE_DEVICE_UNKNOWN, \fBDIO_IOCODE_SET_PORTACCESS\fP, METHOD_BUFFERED, FILE_ANY_ACCESS)"
.br
.ti -1c
.RI "#define \fBDIO_IOCTL_RESET_PORTACCESS\fP   CTL_CODE(FILE_DEVICE_UNKNOWN, \fBDIO_IOCODE_RESET_PORTACCESS\fP, METHOD_BUFFERED, FILE_ANY_ACCESS)"
.br
.ti -1c
.RI "#define \fBDIO_PORTACCESS_ENTRY_MAXIMUM\fP   256"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_DIO_PORTACCESS_ENTRY\fP \fBDIO_PORTACCESS_ENTRY\fP"
.br
.RI "Port access entry structure\&. "
.ti -1c
.RI "typedef struct \fB_DIO_PACKET_PORTACCESS\fP \fBDIO_PACKET_PORTACCESS\fP"
.br
.RI "Port access packet structure\&. "
.ti -1c
.RI "typedef union \fB_DIO_PACKET\fP \fBDIO_PACKET\fP"
.br
.RI "IOCTL packet\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBC_ASSERT\fP (sizeof(\fBDIO_PACKET_PORTACCESS\fP)==sizeof(ULONG))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DIO_IOCODE_RESET_PORTACCESS   0x802"

.PP
Definition at line 9 of file dioctl\&.h\&.
.SS "#define DIO_IOCODE_SET_PORTACCESS   0x801"

.PP
Definition at line 8 of file dioctl\&.h\&.
.SS "#define DIO_IOCTL_RESET_PORTACCESS   CTL_CODE(FILE_DEVICE_UNKNOWN, \fBDIO_IOCODE_RESET_PORTACCESS\fP, METHOD_BUFFERED, FILE_ANY_ACCESS)"

.PP
Definition at line 12 of file dioctl\&.h\&.
.SS "#define DIO_IOCTL_SET_PORTACCESS   CTL_CODE(FILE_DEVICE_UNKNOWN, \fBDIO_IOCODE_SET_PORTACCESS\fP, METHOD_BUFFERED, FILE_ANY_ACCESS)"

.PP
Definition at line 11 of file dioctl\&.h\&.
.SS "#define DIO_PORTACCESS_ENTRY_MAXIMUM   256"

.PP
Definition at line 16 of file dioctl\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef union \fB_DIO_PACKET\fP  \fBDIO_PACKET\fP"

.PP
IOCTL packet\&. 
.SS "typedef struct \fB_DIO_PACKET_PORTACCESS\fP  \fBDIO_PACKET_PORTACCESS\fP"

.PP
Port access packet structure\&. Contains one or multiple port address ranges\&.
.br

.SS "typedef struct \fB_DIO_PORTACCESS_ENTRY\fP  \fBDIO_PORTACCESS_ENTRY\fP"

.PP
Port access entry structure\&. Describes port address range\&.
.br

.SH "Function Documentation"
.PP 
.SS "C_ASSERT (sizeof(\fBDIO_PACKET_PORTACCESS\fP) = \fC=sizeof(ULONG)\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIO from the source code\&.
