.TH "DIOTest/main.cpp" 3 "Sun Mar 10 2019" "DIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DIOTest/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <conio\&.h>\fP
.br
\fC#include <intrin\&.h>\fP
.br
\fC#include <Windows\&.h>\fP
.br
\fC#include <Shlwapi\&.h>\fP
.br
\fC#include '\&.\&./Include/dioctl\&.h'\fP
.br
\fC#include 'DriverService\&.h'\fP
.br
\fC#include 'PortAccessService\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPortAccessTest\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 60 of file main\&.cpp\&.
.SS "void PortAccessTest ()"

.PP
Definition at line 16 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DIO from the source code\&.
